# golangci-lint v2 configuration
# https://golangci-lint.run/docs/product/migration-guide

version: "2"

linters:
  default: none  # Start with no linters
  enable:
    - govet
    - ineffassign
  # Disabled for now - require significant fixes:
  # - errcheck (500+ unchecked errors)
  # - unused (30+ intentionally unused code)
  # - staticcheck (11 SA9003 empty branch issues)
  exclusions:
    paths:
      - ".*_test\\.go$"
      - ".pr-review"
      - "dist"
      - "site"
      - "demos"
      - ".*_generated\\.go$"
      - ".*\\.pb\\.go$"
    generated: strict

run:
  go: '1.24'
  timeout: 5m
