version: 2

linters-settings:
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: reviewtask
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc

linters:
  enable:
    - gofmt
    - typecheck

  # Disable strict linters for initial CI setup
  disable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - goconst
    - gocritic
    - goimports
    - gosec
    - misspell
    - nakedret
    - prealloc
    - unconvert
    - unparam
    - unused
    - whitespace

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

issues:
  exclude-dirs:
    - dist
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - govet
    
    # Exclude some staticcheck messages
    - linters:
        - staticcheck
      text: "SA9003:"
    
    # Exclude lll issues for long lines of comments
    - linters:
        - lll
      source: "^//.*$"

  max-issues-per-linter: 0
  max-same-issues: 0
