version: "2"

formatters:
  enable:
    - gofmt
  settings:
    goimports:
      local-prefixes:
        - reviewtask

linters:
  # Disable strict linters for initial CI setup
  disable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - goconst
    - gocritic
    - gosec
    - misspell
    - nakedret
    - prealloc
    - unconvert
    - unparam
    - unused
    - whitespace

  exclusions:
    paths:
      - dist
    rules:
      - path: _test\.go
        linters:
          - gocyclo
          - errcheck
          - dupl
          - gosec
          - govet

      # Exclude some staticcheck messages
      - linters:
          - staticcheck
        text: "SA9003:"

      # Exclude lll issues for long lines of comments
      - linters:
          - lll
        source: "^//.*$"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0