site_name: reviewtask - AI-Powered PR Review Management Tool
site_description: A CLI tool that fetches GitHub Pull Request reviews, analyzes them using AI, and generates actionable tasks for developers to address feedback systematically.
site_author: biwakonbu
site_url: https://biwakonbu.github.io/reviewtask/

repo_name: biwakonbu/reviewtask
repo_url: https://github.com/biwakonbu/reviewtask
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2024 biwakonbu

theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/icon.png
  custom_dir: docs/overrides
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.code.annotate

  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

plugins:
  - search:
      lang: en
  - social:
      cards: true
      cards_dir: assets/images/social
      cards_layout_options:
        background_color: "#1e88e5"
        color: "#FFFFFF"
        font_family: Roboto
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - git-committers:
      repository: biwakonbu/reviewtask
      branch: main

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: biwakonbu
      repo: reviewtask
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - User Guide:
    - Overview: user-guide/README.md
    - Installation: user-guide/installation.md
    - Quick Start: user-guide/quick-start.md
    - Authentication: user-guide/authentication.md
    - Commands: user-guide/commands.md
    - Configuration: user-guide/configuration.md
    - Workflow: user-guide/workflow.md
    - Troubleshooting: user-guide/troubleshooting.md
  - Developer Guide:
    - Overview: developer-guide/README.md
    - Architecture: developer-guide/architecture.md
    - Development Setup: developer-guide/development-setup.md
    - Project Structure: developer-guide/project-structure.md
    - Testing: developer-guide/testing.md
    - Contributing: developer-guide/contributing.md
    - Versioning: developer-guide/versioning.md

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/biwakonbu/reviewtask
    - icon: fontawesome/solid/globe
      link: https://biwakonbu.github.io/reviewtask/
  generator: false

extra_css:
  - assets/stylesheets/extra.css

copyright: Copyright &copy; 2024 biwakonbu