site_name: reviewtask - AI-Powered PR Review Management Tool
site_description: A CLI tool that fetches GitHub Pull Request reviews, analyzes them using AI, and generates actionable tasks for developers to address feedback systematically.
site_author: biwakonbu
site_url: https://biwakonbu.github.io/reviewtask/

repo_name: biwakonbu/reviewtask
repo_url: https://github.com/biwakonbu/reviewtask
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2024 biwakonbu

theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.code.annotate

  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

plugins:
  - search:
      lang: en
  - social:
      cards: true
      cards_color:
        fill: "#1e88e5"
        text: "#FFFFFF"
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - git-committers:
      repository: biwakonbu/reviewtask
      branch: main

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: biwakonbu
      repo: reviewtask
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - Quick Start: quick-start.md
    - Authentication: authentication.md
  - User Guide:
    - Commands: commands.md
    - Configuration: configuration.md
    - Workflow: workflow.md
    - Troubleshooting: troubleshooting.md
  - Development:
    - Contributing: contributing.md
    - Architecture: architecture.md
    - Versioning: versioning.md
    - Project Vision: prd.md
  - Implementation Details:
    - Progress: implementation-progress.md
    - Issue #140: issue-140-implementation.md

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/biwakonbu/reviewtask
    - icon: fontawesome/solid/globe
      link: https://biwakonbu.github.io/reviewtask/
  # OGP settings
  og:
    title: reviewtask - AI-Powered PR Review Management
    type: website
    description: Transform GitHub PR reviews into actionable tasks with AI
    image: !ENV [SITE_URL, 'https://biwakonbu.github.io/reviewtask/']/assets/images/social/index.png
    locale: en_US
  twitter:
    card: summary_large_image
    title: reviewtask - AI-Powered PR Review Management
    description: Transform GitHub PR reviews into actionable tasks with AI
    image: !ENV [SITE_URL, 'https://biwakonbu.github.io/reviewtask/']/assets/images/social/index.png

copyright: Copyright &copy; 2024 biwakonbu